// E00-S03 import-fidelity proof tests.
//
// Golden expectations come from proof/import/fixtures/manifest.json, which
// was specified by hand from the fixture bytes and declared profiles — never
// generated by the parser. Hostile and resource-bound cases run inside the
// isolated parser child via runBoundedParse so the suite also proves the
// parent survives bounded failures.

import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import { runBoundedParse } from "../proof/import/bounds.ts";
import { buildXlsx, type FixtureCell } from "../proof/import/build-xlsx.ts";
import {
  buildPrior,
  decideReimport,
  parseAmountToMinor,
  parseDateToIso,
  parseImportFile,
  type ImportProfile,
  type Proposal,
} from "../proof/import/parser.ts";

// The suite runs from the repository root for every documented command.
const ROOT = process.cwd();
const FIX = join(ROOT, "proof", "import", "fixtures");
const MANIFEST = JSON.parse(readFileSync(join(FIX, "manifest.json"), "utf-8")) as Manifest;

type ExpectedAccepted = {
  row: number;
  date: string;
  description: string;
  amountMinor: string;
  currency: string;
  direction: string;
};
type ExpectedReview = { row: number; reasons: string[] };
type CsvFixture = {
  id: string;
  file: string;
  profile: ImportProfile;
  expected: { accepted: ExpectedAccepted[]; needsReview: ExpectedReview[]; rejected: ExpectedReview[] };
};
type XlsxBuild = {
  header: string[];
  rows: { kind: string; value?: string; expression?: string; cached?: string }[][];
};
type XlsxFixture = {
  id: string;
  sheet: string;
  externalLink?: boolean;
  profile: ImportProfile;
  build: XlsxBuild;
  expected: CsvFixture["expected"] | { fileError: string };
};
type Manifest = { csvFixtures: CsvFixture[]; xlsxFixtures: XlsxFixture[] };

function comparable(p: Proposal): unknown {
  if (p.kind === "accepted") {
    return {
      kind: p.kind,
      rowNumber: p.rowNumber,
      amountMinor: p.amountMinor,
      currency: p.currency,
      direction: p.direction,
      effectiveDate: p.effectiveDate,
      description: p.description,
    };
  }
  return { kind: p.kind, rowNumber: p.rowNumber, reasons: p.reasons };
}

function expectedComparable(fx: CsvFixture["expected"]): unknown[] {
  const out: unknown[] = [];
  for (const a of fx.accepted) {
    out.push({
      kind: "accepted",
      rowNumber: a.row,
      amountMinor: a.amountMinor,
      currency: a.currency,
      direction: a.direction,
      effectiveDate: a.date,
      description: a.description,
    });
  }
  for (const r of fx.needsReview) out.push({ kind: "needs_review", rowNumber: r.row, reasons: r.reasons });
  for (const r of fx.rejected) out.push({ kind: "rejected", rowNumber: r.row, reasons: r.reasons });
  return out.sort((x, y) => (x as { rowNumber: number }).rowNumber - (y as { rowNumber: number }).rowNumber);
}

function toFixtureCells(rows: XlsxBuild["rows"]): FixtureCell[][] {
  return rows.map((row) =>
    row.map((c): FixtureCell => {
      if (c.kind === "formula") return { kind: "formula", expression: c.expression ?? "", cached: c.cached ?? "" };
      if (c.kind === "number") return { kind: "number", value: c.value ?? "" };
      return { kind: "text", value: c.value ?? "" };
    }),
  );
}

describe("E00-S03 CSV golden fixtures (manifest oracle)", () => {
  for (const fx of MANIFEST.csvFixtures) {
    it(`${fx.id} matches hand-specified expectations exactly`, () => {
      const bytes = new Uint8Array(readFileSync(join(FIX, fx.file)));
      const res = parseImportFile(bytes, fx.file, fx.profile);
      expect(res.ok).toBe(true);
      if (!res.ok) return;
      expect(res.sheet).toBeNull();
      const got = res.proposals.map(comparable).sort((x, y) => (x as { rowNumber: number }).rowNumber - (y as { rowNumber: number }).rowNumber);
      expect(got).toEqual(expectedComparable(fx.expected));
      for (const p of res.proposals) {
        expect(p.source.file).toBe(fx.file);
        expect(p.source.row).toBe(p.rowNumber);
        expect(p.observationId).toMatch(/^[0-9a-f]{16}$/);
      }
    });
  }
});

describe("E00-S03 XLSX golden fixtures (manifest oracle)", () => {
  for (const fx of MANIFEST.xlsxFixtures) {
    it(`${fx.id} matches hand-specified expectations exactly`, () => {
      const bytes = buildXlsx(
        { name: fx.sheet, header: fx.build.header, rows: toFixtureCells(fx.build.rows) },
        { externalLink: fx.externalLink ?? false },
      );
      const label = `${fx.id}.xlsx`;
      const res = parseImportFile(bytes, label, fx.profile);
      if ("fileError" in fx.expected) {
        expect(res.ok).toBe(false);
        if (res.ok) return;
        expect(res.error.code).toBe(fx.expected.fileError);
        return;
      }
      expect(res.ok).toBe(true);
      if (!res.ok) return;
      expect(res.sheet).toBe(fx.sheet);
      expect(res.ignoredSheets).toBe(0);
      const got = res.proposals.map(comparable).sort((x, y) => (x as { rowNumber: number }).rowNumber - (y as { rowNumber: number }).rowNumber);
      expect(got).toEqual(expectedComparable(fx.expected));
      for (const p of res.proposals) {
        expect(p.source.sheet).toBe(fx.sheet);
        if (p.kind === "needs_review") {
          // Cached formula values must never leak into review rows.
          expect("amountMinor" in p).toBe(false);
        }
      }
    });
  }
});

describe("E00-S03 observation identity and reimport decisions", () => {
  const profileOf = (id: string): ImportProfile => {
    const fx = MANIFEST.csvFixtures.find((f) => f.id === id);
    if (!fx) throw new Error(`fixture ${id} missing`);
    return fx.profile;
  };

  it("observation ids are deterministic and distinct per source row", () => {
    const bytes = new Uint8Array(readFileSync(join(FIX, "duplicates-within-file.csv")));
    const first = parseImportFile(bytes, "duplicates-within-file.csv", profileOf("duplicates-within-file"));
    const second = parseImportFile(bytes, "duplicates-within-file.csv", profileOf("duplicates-within-file"));
    expect(first.ok && second.ok).toBe(true);
    if (!first.ok || !second.ok) return;
    const ids1 = first.proposals.map((p) => p.observationId);
    const ids2 = second.proposals.map((p) => p.observationId);
    expect(ids1).toEqual(ids2);
    // Identical legitimate rows keep multiplicity: two accepted proposals,
    // two distinct observations.
    expect(first.proposals.filter((p) => p.kind === "accepted")).toHaveLength(2);
    expect(new Set(ids1).size).toBe(2);
  });

  it("reimporting the same bytes creates no new effects", () => {
    const bytes = new Uint8Array(readFileSync(join(FIX, "overlap-a.csv")));
    const parsed = parseImportFile(bytes, "overlap-a.csv", profileOf("overlap-a"));
    expect(parsed.ok).toBe(true);
    if (!parsed.ok) return;
    const prior = buildPrior(parsed.proposals);
    const again = parseImportFile(bytes, "overlap-a.csv", profileOf("overlap-a"));
    expect(again.ok).toBe(true);
    if (!again.ok) return;
    const { decisions } = decideReimport(again.proposals, {
      observationIds: prior.observationIds,
      keys: prior.keys,
    });
    expect(decisions.map((d) => d.decision)).toEqual(["matched_existing", "matched_existing"]);
  });

  it("overlapping statements stage ambiguous rows for review instead of guessing", () => {
    const aBytes = new Uint8Array(readFileSync(join(FIX, "overlap-a.csv")));
    const bBytes = new Uint8Array(readFileSync(join(FIX, "overlap-b.csv")));
    const a = parseImportFile(aBytes, "overlap-a.csv", profileOf("overlap-a"));
    const b = parseImportFile(bBytes, "overlap-b.csv", profileOf("overlap-b"));
    expect(a.ok && b.ok).toBe(true);
    if (!a.ok || !b.ok) return;
    const { decisions, proposals } = decideReimport(b.proposals, buildPrior(a.proposals));
    expect(decisions.map((d) => d.decision)).toEqual(["overlap_candidate", "new"]);
    expect(proposals[0]!.kind).toBe("needs_review");
    expect((proposals[0] as { reasons: string[] }).reasons).toEqual(["possible-overlap"]);
    expect(proposals[1]!.kind).toBe("accepted");
  });
});

describe("E00-S03 strict amount and date primitives", () => {
  it("rejects bad thousands grouping without guessing", () => {
    const fmt = { decimalSep: "." as const, thousandsSep: "," as const };
    expect(parseAmountToMinor("12,34,56", fmt, 2)).toEqual({ ok: false, reason: "ambiguous-amount" });
    expect(parseAmountToMinor("1,234.56", fmt, 2)).toEqual({ ok: true, minor: "123456", negative: false, isZero: false });
    expect(parseAmountToMinor("-0.00", fmt, 2)).toMatchObject({ ok: true, isZero: true });
  });

  it("keeps values above the JS safe-integer range exact", () => {
    const fmt = { decimalSep: "." as const, thousandsSep: "" as const };
    expect(parseAmountToMinor("9007199254740993", fmt, 0)).toEqual({
      ok: true,
      minor: "9007199254740993",
      negative: false,
      isZero: false,
    });
    expect(parseAmountToMinor("123456789012345.678", fmt, 3).ok).toBe(true);
  });

  it("never guesses dates", () => {
    expect(parseDateToIso("01/02/2024", "iso")).toEqual({ ok: false, reason: "ambiguous-date" });
    expect(parseDateToIso("30.02.2024", "de")).toEqual({ ok: false, reason: "invalid-date" });
    expect(parseDateToIso("45413", "excel-serial")).toEqual({ ok: true, iso: "2024-05-01" });
    expect(parseDateToIso("45413.5", "excel-serial")).toEqual({ ok: false, reason: "ambiguous-date" });
  });
});

describe("E00-S03 hostile inputs fail bounded inside the isolated child", () => {
  const tmp = () => mkdtempSync(join(tmpdir(), "moneo-s03-"));
  const profileOf = (id: string): ImportProfile => {
    const fx = MANIFEST.csvFixtures.find((f) => f.id === id);
    if (!fx) throw new Error(`fixture ${id} missing`);
    return fx.profile;
  };

  it("corrupt CSV and truncated XLSX are rejected without harming the parent", () => {
    const dir = tmp();
    const badCsv = join(dir, "bad.csv");
    writeFileSync(badCsv, 'date,description,amount\n2024-01-01,"never closed,10.00\n');
    const csvOut = runBoundedParse({ file: badCsv, filename: "bad.csv", profile: profileOf("overlap-a") });
    expect(csvOut.timedOut).toBe(false);
    // Bounded file rejections are normal proof outcomes: exit 0 with a
    // structured body. Nonzero exits are reserved for unexpected child
    // failure (exit 2/3) and kills (timeout signal).
    expect(csvOut.exitCode).toBe(0);
    expect(csvOut.body).toMatchObject({ ok: false, error: { code: "corrupt" } });

    const good = buildXlsx({
      name: "S",
      header: ["date", "description", "amount"],
      rows: [[{ kind: "text", value: "2024-01-01" }, { kind: "text", value: "x" }, { kind: "number", value: "1" }]],
    });
    const cut = join(dir, "cut.xlsx");
    writeFileSync(cut, good.subarray(0, 120));
    const xlsxOut = runBoundedParse({ file: cut, filename: "cut.xlsx", profile: profileOf("overlap-a") });
    expect(xlsxOut.timedOut).toBe(false);
    expect(xlsxOut.body).toMatchObject({ ok: false });
    expect(["corrupt", "unsupported-format"]).toContain(
      (xlsxOut.body!["error"] as { code: string }).code,
    );

    // The parent is unaffected: a healthy parse still succeeds afterwards.
    const healthy = join(dir, "ok.csv");
    writeFileSync(healthy, readFileSync(join(FIX, "overlap-a.csv")));
    const ok = runBoundedParse({ file: healthy, filename: "ok.csv", profile: profileOf("overlap-a") });
    expect(ok.body).toMatchObject({ ok: true });
  });

  it("unsupported formats and schemas get actionable rejections", () => {
    const dir = tmp();
    const pdf = join(dir, "statement.pdf");
    writeFileSync(pdf, "%PDF-1.4 synthetic\n");
    const fmt = runBoundedParse({ file: pdf, filename: "statement.pdf", profile: profileOf("overlap-a") });
    expect(fmt.body).toMatchObject({ ok: false, error: { code: "unsupported-format" } });

    const noschema = join(dir, "noschema.csv");
    writeFileSync(noschema, "when,what,howmuch\n2024-01-01,x,1.00\n");
    const schema = runBoundedParse({ file: noschema, filename: "noschema.csv", profile: profileOf("overlap-a") });
    expect(schema.body).toMatchObject({ ok: false, error: { code: "unsupported-schema" } });
  });

  it("oversized, over-row and over-column files fail fast within bounds", () => {
    const dir = tmp();
    const big = join(dir, "big.csv");
    const line = "2024-01-01,Synthetic padding row for the upload-limit probe,-1.00\n";
    const repeats = Math.ceil((21 * 1024 * 1024) / line.length);
    writeFileSync(big, `date,description,amount\n${line.repeat(repeats)}`);
    const over = runBoundedParse({ file: big, filename: "big.csv", profile: profileOf("overlap-a") });
    expect(over.body).toMatchObject({ ok: false, error: { code: "upload-limit" } });
    expect(over.wallMs).toBeLessThan(30_000);

    const manyRows = join(dir, "rows.csv");
    let rows = "date,description,amount\n";
    for (let i = 0; i < 100_001; i++) rows += `2024-01-01,Row ${i},-1.00\n`;
    writeFileSync(manyRows, rows);
    const rowOut = runBoundedParse({ file: manyRows, filename: "rows.csv", profile: profileOf("overlap-a") });
    expect(rowOut.body).toMatchObject({ ok: false, error: { code: "row-limit" } });

    const wide = join(dir, "wide.csv");
    const header = Array.from({ length: 51 }, (_, i) => `c${i}`).join(",");
    writeFileSync(wide, `${header}\n${Array.from({ length: 51 }, () => "x").join(",")}\n`);
    const colOut = runBoundedParse({ file: wide, filename: "wide.csv", profile: profileOf("overlap-a") });
    expect(colOut.body).toMatchObject({ ok: false, error: { code: "column-limit" } });
  }, 60_000);

  it("expansion bombs abort on the decompressed cap without exhausting the host", () => {
    const dir = tmp();
    // ~12 MiB of incompressible-looking repetition inside one shared string;
    // it compresses to kilobytes on disk but must inflate past the 1 MiB
    // override cap, proving the streaming abort path.
    const bomb = buildXlsx({
      name: "Bomb",
      header: ["date", "description", "amount"],
      rows: [
        [
          { kind: "text", value: "2024-01-01" },
          { kind: "text", value: `payload-${"x".repeat(12 * 1024 * 1024)}` },
          { kind: "number", value: "1" },
        ],
      ],
    });
    expect(bomb.length).toBeLessThan(1024 * 1024);
    const bombFile = join(dir, "bomb.xlsx");
    writeFileSync(bombFile, bomb);
    const out = runBoundedParse({
      file: bombFile,
      filename: "bomb.xlsx",
      profile: profileOf("overlap-a"),
      limits: { maxDecompressedBytes: 1024 * 1024 },
    });
    expect(out.timedOut).toBe(false);
    expect(out.body).toMatchObject({ ok: false, error: { code: "decompressed-limit" } });
  }, 60_000);

  it("a runaway parse is killed on deadline and the parent recovers", () => {
    const dir = tmp();
    const healthy = join(dir, "ok.csv");
    writeFileSync(healthy, readFileSync(join(FIX, "overlap-a.csv")));
    const stuck = runBoundedParse({
      file: healthy,
      filename: "ok.csv",
      profile: profileOf("overlap-a"),
      timeoutMs: 800,
      hangMs: 5_000,
    });
    expect(stuck.timedOut).toBe(true);
    const after = runBoundedParse({ file: healthy, filename: "ok.csv", profile: profileOf("overlap-a") });
    expect(after.timedOut).toBe(false);
    expect(after.body).toMatchObject({ ok: true });
    const heap = after.body!["heapUsedBytes"] as number;
    expect(heap).toBeGreaterThan(0);
    expect(heap).toBeLessThan(256 * 1024 * 1024);
  }, 60_000);
});
