import { test, expect } from "@playwright/test";
import { e2eStorageStatePath, gatedSkipReason, hasSupabaseEnv } from "./fixtures";
const state = e2eStorageStatePath();
if (state) test.use({ storageState: state });
test.skip(!hasSupabaseEnv() || !state, gatedSkipReason());
test("current cash reservations persist and undo without claiming recorded savings", async ({ page }) => {
  test.setTimeout(90_000);
  const suffix = crypto.randomUUID().slice(0, 8), accountName = `Reservation cash ${suffix}`, goalName = `Reservation goal ${suffix}`;
  await page.goto("/");
  await page.getByLabel("Account name", { exact: true }).fill(accountName);
  await page.getByRole("button", { name: "Add account", exact: true }).click();
  const account = page.locator("article").filter({ has: page.getByRole("heading", { name: accountName, exact: true }) });
  await expect(account).toBeVisible({ timeout: 30_000 });
  await account.getByLabel(`${accountName} balance`, { exact: true }).fill("500.00");
  await account.getByRole("button", { name: "Save", exact: true }).click();
  await expect(account).toContainText("EUR 500.00", { timeout: 30_000 });
  await page.goto("/plan");
  await page.getByPlaceholder("Goal name", { exact: true }).fill(goalName);
  await page.getByPlaceholder("Target amount", { exact: true }).fill("500.00");
  await page.getByRole("button", { name: "Add goal", exact: true }).click();
  const goal = page.locator("article").filter({ has: page.getByRole("heading", { name: goalName, exact: true }) });
  await expect(goal).toBeVisible({ timeout: 30_000 });
  await goal.getByText("Reserve or release cash", { exact: true }).click();
  const form = goal.locator("form").filter({ has: page.getByLabel(`${accountName} reservation (EUR)`, { exact: true }) });
  await form.getByLabel(`${accountName} reservation (EUR)`, { exact: true }).fill("100.00");
  await form.getByRole("button", { name: "Set reservation", exact: true }).click();
  await expect(goal).toContainText("Virtual cash reservations: EUR 100.00", { timeout: 30_000 });
  await expect(goal).toContainText("Recorded savings: Unknown");
  await page.reload();
  await expect(goal).toContainText("Virtual cash reservations: EUR 100.00");
  await page.getByText("Reservation history and undo", { exact: true }).click();
  const event = page.locator("li").filter({ hasText: `${goalName}: EUR 0.00 ? EUR 100.00` });
  await event.getByRole("button", { name: "Undo reservation", exact: true }).click();
  await expect(goal).toContainText("Virtual cash reservations: EUR 0.00", { timeout: 30_000 });
  await expect(goal).toContainText("Recorded savings: Unknown");
});
