import { scheduleCadences } from "@/lib/finance/cadences";
import { requireWorkspace } from "@/lib/auth";
import { formatInputAmount, formatMoney } from "@/lib/finance/format";
import { removeScenarioRecord, undoScenarioRecord, updateScenario, updateScenarioEvent } from "./scenario-actions";

type Scenario = { id: string; name: string; description: string | null; version: number };
const field = "mt-1 w-full rounded-lg border border-border bg-card px-3 py-2 text-sm";
function Metadata({ id, version }: { id: string; version: number }) {
  return <><input type="hidden" name="recordId" value={id} /><input type="hidden" name="version" value={version} /><input type="hidden" name="requestId" value={crypto.randomUUID()} /></>;
}
export async function ScenarioEditor({ scenario }: { scenario: Scenario }) {
  const { supabase, workspace } = await requireWorkspace();
  const { data: events, error } = await supabase.from("scenario_overrides").select("id, name, amount_delta_minor::text, currency_code, cadence, starts_on, ends_on, version").eq("workspace_id", workspace.id).eq("scenario_id", scenario.id).is("removed_at", null).order("starts_on").order("id");
  if (error) throw error;
  return <div key={`${scenario.id}:${scenario.version}`} className="mt-4 space-y-3"><details><summary className="cursor-pointer underline">Edit {scenario.name}</summary><form action={updateScenario} className="mt-3 grid gap-3 sm:grid-cols-2"><Metadata id={scenario.id} version={scenario.version} /><label className="text-sm">Scenario name<input name="name" defaultValue={scenario.name} required maxLength={120} className={field} /></label><label className="text-sm">Description<textarea name="description" defaultValue={scenario.description ?? ""} maxLength={1000} className={field} /></label><button className="rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground">Save scenario</button></form><form action={removeScenarioRecord} className="mt-3"><Metadata id={scenario.id} version={scenario.version} /><input type="hidden" name="entityType" value="scenario" /><button className="text-sm text-brand underline">Remove scenario</button></form></details>
    <ul className="space-y-3">{(events ?? []).map(event => <li key={`${event.id}:${event.version}`} className="rounded border border-border p-3"><p className="text-sm font-medium">{event.name} · {formatMoney(event.amount_delta_minor, event.currency_code, workspace.locale)} · {event.cadence} from {event.starts_on}{event.ends_on ? ` until ${event.ends_on}` : ""}</p><details className="mt-2"><summary className="cursor-pointer text-sm underline">Edit scenario event</summary><form action={updateScenarioEvent} className="mt-3 grid gap-3 sm:grid-cols-2"><Metadata id={event.id} version={event.version} /><label className="text-sm">Event name<input name="name" required maxLength={120} defaultValue={event.name} className={field} /></label><label className="text-sm">Change ({event.currency_code})<input name="amount" required defaultValue={formatInputAmount(event.amount_delta_minor, event.currency_code)} className={field} /></label><label className="text-sm">Cadence<select name="cadence" defaultValue={event.cadence} className={field}>{scheduleCadences.map(value => <option key={value}>{value}</option>)}</select></label><label className="text-sm">Starts<input type="date" name="startsOn" required defaultValue={event.starts_on} className={field} /></label><label className="text-sm">Ends<input type="date" name="endsOn" defaultValue={event.ends_on ?? ""} className={field} /></label><button className="rounded bg-primary px-3 py-2 text-sm text-primary-foreground">Save scenario event</button></form></details><form action={removeScenarioRecord} className="mt-2"><Metadata id={event.id} version={event.version} /><input type="hidden" name="entityType" value="override" /><button className="text-sm text-brand underline">Remove scenario event</button></form></li>)}</ul>{!events?.length && <p className="text-sm text-muted-foreground">No changes in this scenario yet. Add one below.</p>}
  </div>;
}
export async function ScenarioHistory() {
  const { supabase, workspace } = await requireWorkspace();
  const [history, scenarios, overrides] = await Promise.all([
    supabase.from("scenario_events").select("id, entity_type, entity_id, before, after, undone, created_at").eq("workspace_id", workspace.id).order("created_at", { ascending: false }).limit(50),
    supabase.from("scenarios").select("id, version").eq("workspace_id", workspace.id),
    supabase.from("scenario_overrides").select("id, version").eq("workspace_id", workspace.id),
  ]);
  for (const error of [history.error, scenarios.error, overrides.error]) if (error) throw error;
  const versions = new Map([...(scenarios.data ?? []), ...(overrides.data ?? [])].map(record => [record.id, record.version]));
  return <details className="rounded-xl border border-border bg-card p-5"><summary className="cursor-pointer font-semibold">Scenario history and undo</summary><p className="mt-2 text-xs text-muted-foreground">Last 50 changes. Undo in reverse order. Restoring or removing a scenario never changes actual transactions or cash reservations.</p><ul className="mt-3 space-y-3">{(history.data ?? []).map(event => { const after = event.after as { name: string; amount_delta_minor?: string; currency_code?: string; removed_at: string | null }; return <li key={event.id} className="flex flex-wrap items-center justify-between gap-3 rounded border border-border p-3 text-sm"><div><p>{after.name}{after.amount_delta_minor && after.currency_code ? ` · ${formatMoney(after.amount_delta_minor, after.currency_code, workspace.locale)}` : ""}</p><p className="text-xs text-muted-foreground">{new Date(event.created_at).toLocaleString(workspace.locale, { timeZone: workspace.timezone })} · {event.undone ? "Undone" : after.removed_at ? "Removed" : event.before ? "Changed" : "Created"}</p></div>{!event.undone && <form action={undoScenarioRecord}><input type="hidden" name="eventId" value={event.id} /><input type="hidden" name="version" value={versions.get(event.entity_id)} /><button className="text-brand underline">Undo scenario change</button></form>}</li>; })}</ul></details>;
}
