-- Epoch 6: durable conversations, runs, gateway traces and account AI policy.
CREATE TABLE conversations (id uuid PRIMARY KEY DEFAULT uuid_generate_v7(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, title text NOT NULL DEFAULT 'New conversation', pinned boolean NOT NULL DEFAULT false, context jsonb NOT NULL DEFAULT '{}', ai_policy_version integer NOT NULL DEFAULT 1, created_at timestamp with time zone NOT NULL DEFAULT now(), updated_at timestamp with time zone NOT NULL DEFAULT now());
--> statement-breakpoint
CREATE TABLE messages (id uuid PRIMARY KEY DEFAULT uuid_generate_v7(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, conversation_id uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, role text NOT NULL, content jsonb NOT NULL, ai_policy_version integer NOT NULL DEFAULT 1, created_at timestamp with time zone NOT NULL DEFAULT now(), CONSTRAINT messages_role_check CHECK (role IN ('user', 'assistant', 'tool')));
--> statement-breakpoint
CREATE TABLE ai_capabilities (id uuid PRIMARY KEY DEFAULT uuid_generate_v7(), key text NOT NULL UNIQUE, created_at timestamp with time zone NOT NULL DEFAULT now());
--> statement-breakpoint
CREATE TABLE ai_capability_versions (id uuid PRIMARY KEY DEFAULT uuid_generate_v7(), capability_id uuid NOT NULL REFERENCES ai_capabilities(id) ON DELETE CASCADE, version integer NOT NULL, configuration jsonb NOT NULL, created_at timestamp with time zone NOT NULL DEFAULT now(), CONSTRAINT ai_capability_versions_capability_version_uniq UNIQUE(capability_id, version));
--> statement-breakpoint
CREATE TABLE workspace_ai_config (workspace_id uuid PRIMARY KEY REFERENCES workspaces(id) ON DELETE CASCADE, mode text NOT NULL DEFAULT 'included', credential_ciphertext text, credential_version integer NOT NULL DEFAULT 1, ai_policy_version integer NOT NULL DEFAULT 1, updated_at timestamp with time zone NOT NULL DEFAULT now(), CONSTRAINT workspace_ai_config_mode_check CHECK (mode IN ('included', 'custom')));
--> statement-breakpoint
CREATE TABLE workspace_ai_capability_overrides (workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, capability_id uuid NOT NULL REFERENCES ai_capabilities(id) ON DELETE CASCADE, configuration jsonb NOT NULL, updated_at timestamp with time zone NOT NULL DEFAULT now(), PRIMARY KEY(workspace_id, capability_id));
--> statement-breakpoint
CREATE TABLE ai_runs (id uuid PRIMARY KEY DEFAULT uuid_generate_v7(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, conversation_id uuid REFERENCES conversations(id) ON DELETE SET NULL, capability_version_id uuid REFERENCES ai_capability_versions(id), status text NOT NULL DEFAULT 'queued', ai_policy_version integer NOT NULL, budget jsonb NOT NULL, error jsonb, started_at timestamp with time zone, finished_at timestamp with time zone, created_at timestamp with time zone NOT NULL DEFAULT now(), CONSTRAINT ai_runs_status_check CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')));
--> statement-breakpoint
CREATE TABLE ai_model_calls (id uuid PRIMARY KEY DEFAULT uuid_generate_v7(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, run_id uuid NOT NULL REFERENCES ai_runs(id) ON DELETE CASCADE, requested_model text NOT NULL, resolved_model text, resolved_provider text, input_tokens integer, output_tokens integer, cached_tokens integer, cost_micros bigint, latency_ms integer, finish_reason text, created_at timestamp with time zone NOT NULL DEFAULT now());
--> statement-breakpoint
CREATE TABLE ai_tool_calls (id uuid PRIMARY KEY DEFAULT uuid_generate_v7(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, run_id uuid NOT NULL REFERENCES ai_runs(id) ON DELETE CASCADE, tool_name text NOT NULL, input jsonb NOT NULL, output jsonb, status text NOT NULL DEFAULT 'queued', created_at timestamp with time zone NOT NULL DEFAULT now(), CONSTRAINT ai_tool_calls_status_check CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')));
--> statement-breakpoint
CREATE TABLE workspace_ai_access_policies (workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, account_id uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE, ai_access boolean NOT NULL DEFAULT true, policy_version integer NOT NULL, updated_at timestamp with time zone NOT NULL DEFAULT now(), PRIMARY KEY(workspace_id, account_id));
--> statement-breakpoint
CREATE INDEX conversations_workspace_updated_idx ON conversations(workspace_id, updated_at); CREATE INDEX messages_conversation_created_idx ON messages(conversation_id, created_at); CREATE INDEX ai_runs_workspace_created_idx ON ai_runs(workspace_id, created_at);
--> statement-breakpoint
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY; ALTER TABLE messages ENABLE ROW LEVEL SECURITY; ALTER TABLE workspace_ai_config ENABLE ROW LEVEL SECURITY; ALTER TABLE workspace_ai_capability_overrides ENABLE ROW LEVEL SECURITY; ALTER TABLE ai_runs ENABLE ROW LEVEL SECURITY; ALTER TABLE ai_model_calls ENABLE ROW LEVEL SECURITY; ALTER TABLE ai_tool_calls ENABLE ROW LEVEL SECURITY; ALTER TABLE workspace_ai_access_policies ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON conversations, messages, workspace_ai_config, workspace_ai_capability_overrides, ai_runs, ai_model_calls, ai_tool_calls, workspace_ai_access_policies TO moneo_app;
--> statement-breakpoint
CREATE POLICY conversations_isolation ON conversations FOR ALL TO moneo_app USING (workspace_id = nullif(current_setting('app.current_workspace', true), '')::uuid) WITH CHECK (workspace_id = nullif(current_setting('app.current_workspace', true), '')::uuid); CREATE POLICY messages_isolation ON messages FOR ALL TO moneo_app USING (workspace_id = nullif(current_setting('app.current_workspace', true), '')::uuid) WITH CHECK (workspace_id = nullif(current_setting('app.current_workspace', true), '')::uuid); CREATE POLICY workspace_ai_config_isolation ON workspace_ai_config FOR ALL TO moneo_app USING (workspace_id = nullif(current_setting('app.current_workspace', true), '')::uuid) WITH CHECK (workspace_id = nullif(current_setting('app.current_workspace', true), '')::uuid); CREATE POLICY workspace_ai_capability_overrides_isolation ON workspace_ai_capability_overrides FOR ALL TO moneo_app USING (workspace_id = nullif(current_setting('app.current_workspace', true), '')::uuid) WITH CHECK (workspace_id = nullif(current_setting('app.current_workspace', true), '')::uuid); CREATE POLICY ai_runs_isolation ON ai_runs FOR ALL TO moneo_app USING (workspace_id = nullif(current_setting('app.current_workspace', true), '')::uuid) WITH CHECK (workspace_id = nullif(current_setting('app.current_workspace', true), '')::uuid); CREATE POLICY ai_model_calls_isolation ON ai_model_calls FOR ALL TO moneo_app USING (workspace_id = nullif(current_setting('app.current_workspace', true), '')::uuid) WITH CHECK (workspace_id = nullif(current_setting('app.current_workspace', true), '')::uuid); CREATE POLICY ai_tool_calls_isolation ON ai_tool_calls FOR ALL TO moneo_app USING (workspace_id = nullif(current_setting('app.current_workspace', true), '')::uuid) WITH CHECK (workspace_id = nullif(current_setting('app.current_workspace', true), '')::uuid); CREATE POLICY workspace_ai_access_policies_isolation ON workspace_ai_access_policies FOR ALL TO moneo_app USING (workspace_id = nullif(current_setting('app.current_workspace', true), '')::uuid) WITH CHECK (workspace_id = nullif(current_setting('app.current_workspace', true), '')::uuid);
