/**
 * ISO 4217 active currency dataset: code, English name, minor-unit exponent.
 * Source: ISO 4217 / SWIFT currency code list conventions.
 *
 * Single canonical copy (Issue 0.9). `@moneo/db` re-exports this module for
 * seeding; all exponent lookups go through `minorDigitsFor` here so import
 * code never hardcodes per-currency precision.
 *
 * XDR, XSU and XUA are intentionally absent: ISO 4217 lists their minor unit
 * as N.A., so no exact minor-unit representation exists for them.
 */
export interface CurrencySeed {
  code: string;
  name: string;
  minorDigits: number;
}

export const CURRENCIES: CurrencySeed[] = [
  { code: "AED", name: "UAE Dirham", minorDigits: 2 },
  { code: "AFN", name: "Afghani", minorDigits: 2 },
  { code: "ALL", name: "Lek", minorDigits: 2 },
  { code: "AMD", name: "Armenian Dram", minorDigits: 2 },
  { code: "ANG", name: "Netherlands Antillean Guilder", minorDigits: 2 },
  { code: "AOA", name: "Kwanza", minorDigits: 2 },
  { code: "ARS", name: "Argentine Peso", minorDigits: 2 },
  { code: "AUD", name: "Australian Dollar", minorDigits: 2 },
  { code: "AWG", name: "Aruban Florin", minorDigits: 2 },
  { code: "AZN", name: "Azerbaijan Manat", minorDigits: 2 },
  { code: "BAM", name: "Convertible Mark", minorDigits: 2 },
  { code: "BBD", name: "Barbados Dollar", minorDigits: 2 },
  { code: "BDT", name: "Taka", minorDigits: 2 },
  { code: "BGN", name: "Bulgarian Lev", minorDigits: 2 },
  { code: "BHD", name: "Bahraini Dinar", minorDigits: 3 },
  { code: "BIF", name: "Burundi Franc", minorDigits: 0 },
  { code: "BMD", name: "Bermudian Dollar", minorDigits: 2 },
  { code: "BND", name: "Brunei Dollar", minorDigits: 2 },
  { code: "BOB", name: "Boliviano", minorDigits: 2 },
  { code: "BOV", name: "Mvdol", minorDigits: 2 },
  { code: "BRL", name: "Brazilian Real", minorDigits: 2 },
  { code: "BSD", name: "Bahamian Dollar", minorDigits: 2 },
  { code: "BTN", name: "Ngultrum", minorDigits: 2 },
  { code: "BWP", name: "Pula", minorDigits: 2 },
  { code: "BYN", name: "Belarusian Ruble", minorDigits: 2 },
  { code: "BZD", name: "Belize Dollar", minorDigits: 2 },
  { code: "CAD", name: "Canadian Dollar", minorDigits: 2 },
  { code: "CDF", name: "Congolese Franc", minorDigits: 2 },
  { code: "CHE", name: "WIR Euro", minorDigits: 2 },
  { code: "CHW", name: "WIR Franc", minorDigits: 2 },
  { code: "CHF", name: "Swiss Franc", minorDigits: 2 },
  { code: "CLP", name: "Chilean Peso", minorDigits: 0 },
  { code: "CNY", name: "Yuan Renminbi", minorDigits: 2 },
  { code: "COP", name: "Colombian Peso", minorDigits: 2 },
  { code: "COU", name: "Unidad de Valor Real", minorDigits: 2 },
  { code: "CRC", name: "Costa Rican Colon", minorDigits: 2 },
  { code: "CUP", name: "Cuban Peso", minorDigits: 2 },
  { code: "CVE", name: "Cabo Verde Escudo", minorDigits: 2 },
  { code: "CZK", name: "Czech Koruna", minorDigits: 2 },
  { code: "DJF", name: "Djibouti Franc", minorDigits: 0 },
  { code: "DKK", name: "Danish Krone", minorDigits: 2 },
  { code: "DOP", name: "Dominican Peso", minorDigits: 2 },
  { code: "DZD", name: "Algerian Dinar", minorDigits: 2 },
  { code: "EGP", name: "Egyptian Pound", minorDigits: 2 },
  { code: "ERN", name: "Nakfa", minorDigits: 2 },
  { code: "ETB", name: "Ethiopian Birr", minorDigits: 2 },
  { code: "EUR", name: "Euro", minorDigits: 2 },
  { code: "FJD", name: "Fiji Dollar", minorDigits: 2 },
  { code: "FKP", name: "Falkland Islands Pound", minorDigits: 2 },
  { code: "GBP", name: "Pound Sterling", minorDigits: 2 },
  { code: "GEL", name: "Lari", minorDigits: 2 },
  { code: "GGP", name: "Guernsey Pound", minorDigits: 2 },
  { code: "GHS", name: "Ghana Cedi", minorDigits: 2 },
  { code: "GIP", name: "Gibraltar Pound", minorDigits: 2 },
  { code: "GMD", name: "Dalasi", minorDigits: 2 },
  { code: "GNF", name: "Guinean Franc", minorDigits: 0 },
  { code: "GTQ", name: "Quetzal", minorDigits: 2 },
  { code: "GYD", name: "Guyana Dollar", minorDigits: 2 },
  { code: "HKD", name: "Hong Kong Dollar", minorDigits: 2 },
  { code: "HNL", name: "Lempira", minorDigits: 2 },
  { code: "HTG", name: "Gourde", minorDigits: 2 },
  { code: "HUF", name: "Forint", minorDigits: 2 },
  { code: "IDR", name: "Rupiah", minorDigits: 2 },
  { code: "ILS", name: "New Israeli Sheqel", minorDigits: 2 },
  { code: "IMP", name: "Manx Pound", minorDigits: 2 },
  { code: "INR", name: "Indian Rupee", minorDigits: 2 },
  { code: "IQD", name: "Iraqi Dinar", minorDigits: 3 },
  { code: "IRR", name: "Iranian Rial", minorDigits: 2 },
  { code: "ISK", name: "Iceland Krona", minorDigits: 0 },
  { code: "JEP", name: "Jersey Pound", minorDigits: 2 },
  { code: "JMD", name: "Jamaican Dollar", minorDigits: 2 },
  { code: "JOD", name: "Jordanian Dinar", minorDigits: 3 },
  { code: "JPY", name: "Yen", minorDigits: 0 },
  { code: "KES", name: "Kenyan Shilling", minorDigits: 2 },
  { code: "KGS", name: "Som", minorDigits: 2 },
  { code: "KHR", name: "Riel", minorDigits: 2 },
  { code: "KMF", name: "Comorian Franc", minorDigits: 0 },
  { code: "KPW", name: "North Korean Won", minorDigits: 2 },
  { code: "KRW", name: "Won", minorDigits: 0 },
  { code: "KWD", name: "Kuwaiti Dinar", minorDigits: 3 },
  { code: "KYD", name: "Cayman Islands Dollar", minorDigits: 2 },
  { code: "KZT", name: "Tenge", minorDigits: 2 },
  { code: "LAK", name: "Lao Kip", minorDigits: 2 },
  { code: "LBP", name: "Lebanese Pound", minorDigits: 2 },
  { code: "LKR", name: "Sri Lanka Rupee", minorDigits: 2 },
  { code: "LRD", name: "Liberian Dollar", minorDigits: 2 },
  { code: "LSL", name: "Loti", minorDigits: 2 },
  { code: "LYD", name: "Libyan Dinar", minorDigits: 3 },
  { code: "MAD", name: "Moroccan Dirham", minorDigits: 2 },
  { code: "MDL", name: "Moldovan Leu", minorDigits: 2 },
  { code: "MGA", name: "Malagasy Ariary", minorDigits: 2 },
  { code: "MKD", name: "Denar", minorDigits: 2 },
  { code: "MMK", name: "Kyat", minorDigits: 2 },
  { code: "MNT", name: "Tugrik", minorDigits: 2 },
  { code: "MOP", name: "Pataca", minorDigits: 2 },
  { code: "MRU", name: "Ouguiya", minorDigits: 2 },
  { code: "MUR", name: "Mauritius Rupee", minorDigits: 2 },
  { code: "MVR", name: "Rufiyaa", minorDigits: 2 },
  { code: "MWK", name: "Malawi Kwacha", minorDigits: 2 },
  { code: "MXN", name: "Mexican Peso", minorDigits: 2 },
  { code: "MXV", name: "Mexican Unidad de Inversion (UDI)", minorDigits: 2 },
  { code: "MYR", name: "Malaysian Ringgit", minorDigits: 2 },
  { code: "MZN", name: "Mozambique Metical", minorDigits: 2 },
  { code: "NAD", name: "Namibia Dollar", minorDigits: 2 },
  { code: "NGN", name: "Naira", minorDigits: 2 },
  { code: "NIO", name: "Cordoba Oro", minorDigits: 2 },
  { code: "NOK", name: "Norwegian Krone", minorDigits: 2 },
  { code: "NPR", name: "Nepalese Rupee", minorDigits: 2 },
  { code: "NZD", name: "New Zealand Dollar", minorDigits: 2 },
  { code: "OMR", name: "Rial Omani", minorDigits: 3 },
  { code: "PAB", name: "Balboa", minorDigits: 2 },
  { code: "PEN", name: "Sol", minorDigits: 2 },
  { code: "PGK", name: "Kina", minorDigits: 2 },
  { code: "PHP", name: "Philippine Peso", minorDigits: 2 },
  { code: "PKR", name: "Pakistan Rupee", minorDigits: 2 },
  { code: "PLN", name: "Zloty", minorDigits: 2 },
  { code: "PYG", name: "Guarani", minorDigits: 0 },
  { code: "QAR", name: "Qatari Rial", minorDigits: 2 },
  { code: "RON", name: "Romanian Leu", minorDigits: 2 },
  { code: "RSD", name: "Serbian Dinar", minorDigits: 2 },
  { code: "RUB", name: "Russian Ruble", minorDigits: 2 },
  { code: "RWF", name: "Rwanda Franc", minorDigits: 0 },
  { code: "SAR", name: "Saudi Riyal", minorDigits: 2 },
  { code: "SBD", name: "Solomon Islands Dollar", minorDigits: 2 },
  { code: "SCR", name: "Seychelles Rupee", minorDigits: 2 },
  { code: "SDG", name: "Sudanese Pound", minorDigits: 2 },
  { code: "SEK", name: "Swedish Krona", minorDigits: 2 },
  { code: "SGD", name: "Singapore Dollar", minorDigits: 2 },
  { code: "SHP", name: "Saint Helena Pound", minorDigits: 2 },
  { code: "SLE", name: "Leone", minorDigits: 2 },
  { code: "SOS", name: "Somali Shilling", minorDigits: 2 },
  { code: "SRD", name: "Surinam Dollar", minorDigits: 2 },
  { code: "SSP", name: "South Sudanese Pound", minorDigits: 2 },
  { code: "STN", name: "Dobra", minorDigits: 2 },
  { code: "SVC", name: "El Salvador Colon", minorDigits: 2 },
  { code: "SYP", name: "Syrian Pound", minorDigits: 2 },
  { code: "SZL", name: "Lilangeni", minorDigits: 2 },
  { code: "THB", name: "Baht", minorDigits: 2 },
  { code: "TJS", name: "Somoni", minorDigits: 2 },
  { code: "TMT", name: "Turkmenistan New Manat", minorDigits: 2 },
  { code: "TND", name: "Tunisian Dinar", minorDigits: 3 },
  { code: "TOP", name: "Pa'anga", minorDigits: 2 },
  { code: "TRY", name: "Turkish Lira", minorDigits: 2 },
  { code: "TTD", name: "Trinidad and Tobago Dollar", minorDigits: 2 },
  { code: "TVD", name: "Tuvalu Dollar", minorDigits: 2 },
  { code: "TWD", name: "New Taiwan Dollar", minorDigits: 2 },
  { code: "TZS", name: "Tanzanian Shilling", minorDigits: 2 },
  { code: "UAH", name: "Hryvnia", minorDigits: 2 },
  { code: "UGX", name: "Uganda Shilling", minorDigits: 0 },
  { code: "USD", name: "US Dollar", minorDigits: 2 },
  { code: "USN", name: "US Dollar (Next day)", minorDigits: 2 },
  { code: "UYU", name: "Peso Uruguayo", minorDigits: 2 },
  { code: "UZS", name: "Uzbekistan Sum", minorDigits: 2 },
  { code: "VED", name: "Bolivar Soberano", minorDigits: 2 },
  { code: "VES", name: "Bolivar Soberano", minorDigits: 2 },
  { code: "VND", name: "Dong", minorDigits: 0 },
  { code: "VUV", name: "Vatu", minorDigits: 0 },
  { code: "WST", name: "Tala", minorDigits: 2 },
  { code: "XAF", name: "CFA Franc BEAC", minorDigits: 0 },
  { code: "XCD", name: "East Caribbean Dollar", minorDigits: 2 },
  { code: "XOF", name: "CFA Franc BCEAO", minorDigits: 0 },
  { code: "XPF", name: "CFP Franc", minorDigits: 0 },
  { code: "YER", name: "Yemeni Rial", minorDigits: 2 },
  { code: "ZAR", name: "Rand", minorDigits: 2 },
  { code: "ZMW", name: "Zambian Kwacha", minorDigits: 2 },
  { code: "ZWL", name: "Zimbabwe Dollar", minorDigits: 2 },
];

export function minorDigitsFor(code: string): number {
  const found = CURRENCIES.find((c) => c.code === code);
  if (!found) throw new Error(`Unknown currency code: ${code}`);
  return found.minorDigits;
}

export function isKnownCurrency(code: string): boolean {
  return CURRENCIES.some((c) => c.code === code);
}
