import { expect, it, vi } from "vitest";
import { POST } from "./route";
import { requireWorkspace } from "@/lib/auth";
import { startFinancialReview } from "@/lib/finance/start-review";
import { DEFAULT_SETTINGS } from "@/lib/settings";
import {resolveReviewRequest} from "@/lib/finance/review-request";
vi.mock("@/lib/auth", () => ({ requireWorkspace: vi.fn() }));
vi.mock("@/lib/ai/provider", () => ({ modelForSettings: vi.fn(async () => ({})), getModel: vi.fn() }));
vi.mock("@/lib/finance/start-review", () => ({ startFinancialReview: vi.fn(async () => ({ jobId: "job", status: "queued" })) }));
it("uses the reviewed request identity and refuses disabled financial data scope", async () => {
  process.env.OPENROUTER_API_KEY = "test"; process.env.SUPABASE_SERVICE_ROLE_KEY = "test"; process.env.NEXT_PUBLIC_SUPABASE_URL = "https://example.test";
  const context = { workspace: { id: "w" }, supabase: {}, settings: DEFAULT_SETTINGS };
  vi.mocked(requireWorkspace).mockResolvedValue(context as unknown as Awaited<ReturnType<typeof requireWorkspace>>);
  const requestId = "00000000-0000-4000-8000-000000000001";
  const request = () => new Request("http://localhost/api/analysis", { method: "POST", body: JSON.stringify({ requestId }) });
  expect((await POST(request())).status).toBe(202);
  expect(startFinancialReview).toHaveBeenCalledWith(context.supabase, "w", requestId, undefined, expect.objectContaining({question: "Review my finances", output: "answer"}));
  vi.mocked(requireWorkspace).mockResolvedValue({ ...context, settings: { ...DEFAULT_SETTINGS, ai_data_scopes: [] } } as unknown as Awaited<ReturnType<typeof requireWorkspace>>);
  expect((await POST(request())).status).toBe(403);
});
it("retains a scoped ordinary question and refuses excessive budgets and disabled requested planning", async () => {
  process.env.OPENROUTER_API_KEY = "test"; process.env.SUPABASE_SERVICE_ROLE_KEY = "test"; process.env.NEXT_PUBLIC_SUPABASE_URL = "https://example.test";
  const context = {workspace: {id: "w"}, supabase: {}, settings: DEFAULT_SETTINGS};
  vi.mocked(requireWorkspace).mockResolvedValue(context as unknown as Awaited<ReturnType<typeof requireWorkspace>>);
  const requestId = "00000000-0000-4000-8000-000000000001";
  const investigation = resolveReviewRequest({version: 1, question: "Run a deep financial review for September", focus: "Subscriptions", query: {version: 1, period: {from: "2026-09-01", to: "2026-09-30"}, groupBy: ["merchant"]}}, "2026-10-07");
  const post = (investigation: unknown) => POST(new Request("http://localhost/api/analysis", {method: "POST", body: JSON.stringify({requestId, investigation})}));
  expect((await post(investigation)).status).toBe(202);
  expect(startFinancialReview).toHaveBeenLastCalledWith(context.supabase, "w", requestId, undefined, investigation);
  expect((await post({...investigation, budget: {...investigation.budget, maxQueries: 999}})).status).toBe(400);
  vi.mocked(requireWorkspace).mockResolvedValue({...context, settings: {...DEFAULT_SETTINGS, ai_data_scopes: ["accounts", "transactions"]}} as unknown as Awaited<ReturnType<typeof requireWorkspace>>);
  expect((await post({...investigation, includePlanning: true})).status).toBe(403);
});
